Syncing charts from release v2.11.0-rc.1

diff --git a/charts/monitoring/prometheus/templates/statefulset.yaml b/charts/monitoring/prometheus/templates/statefulset.yaml
--- a/charts/monitoring/prometheus/templates/statefulset.yaml
+++ b/charts/monitoring/prometheus/templates/statefulset.yaml
@@ -1,25 +1,31 @@
+{{- if not .Values.prometheus.migration.enabled }}
 apiVersion: apps/v1beta2
 kind: StatefulSet
 metadata:
-  name: prometheus-kubermatic
+  name: '{{ template "name" . }}'
 spec:
   replicas: 2
   revisionHistoryLimit: 10
   selector:
     matchLabels:
-      app: prometheus-kubermatic
-  serviceName: prometheus-kubermatic
+      app: {{ template "name" . }}
+  serviceName: '{{ template "name" . }}'
   updateStrategy:
     type: RollingUpdate
   template:
     metadata:
       labels:
-        app: prometheus-kubermatic
+        app: {{ template "name" . }} # deprecated
+        app.kubernetes.io/name: prometheus
+        app.kubernetes.io/instance: {{ template "name" . }}
+        {{- if .Values.prometheus.thanos.enabled }}
+        thanos.io/store-api: 'true'
+        {{- end }}
       annotations:
         kubermatic/scrape: 'true'
         kubermatic/scrape_port: '9090'
         {{- if .Values.prometheus.backup.enabled }}
-        backup.velero.io/backup-volumes: prometheus-backup
+        backup.velero.io/backup-volumes: backup
         pre.hook.backup.velero.io/container: backup
         pre.hook.backup.velero.io/timeout: '{{ .Values.prometheus.backup.timeout | default "60m" }}'
         pre.hook.backup.velero.io/command: '["/bin/sh", "-c", "rm -rf /prometheus/snapshots/* && curl -s -XPOST \"http://127.0.0.1:9090/api/v1/admin/tsdb/snapshot?skip_head=true\" && rsync --archive /prometheus/snapshots/*/ /backup"]'
@@ -27,18 +33,54 @@ spec:
     spec:
       containers:
       - name: prometheus
-        image: 'quay.io/prometheus/prometheus:{{ .Values.prometheus.version }}'
+        image: '{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.version | default .Values.prometheus.image.tag }}'
+        command: [/bin/sh]
         args:
-        - --config.file=/etc/prometheus/config/prometheus.yaml
-        - --storage.tsdb.no-lockfile
-        - --storage.tsdb.path=/var/prometheus/data
-        - --storage.tsdb.retention.time=360h
-        - --web.enable-lifecycle
-        - --web.external-url=https://{{ .Values.prometheus.host | trim }}
-        - --web.route-prefix=/
-        {{- if .Values.prometheus.backup.enabled }}
-        - --web.enable-admin-api
-        {{- end }}
+        - -c
+        - |
+          set -euo pipefail
+
+          echo "Cleaning up block compaction leftovers..."
+          find /var/prometheus/data -type d -name '*.tmp' -maxdepth 1 -print -exec rm -r {} \;
+
+          {{- if .Values.prometheus.thanos.enabled }}
+          config=/etc/prometheus-shared/prometheus.yaml
+
+          echo "Waiting up to 60 seconds for $config..."
+          for i in $(seq 60); do
+            [ -f $config ] && break
+            sleep 1
+          done
+
+          if [ ! -f $config ]; then
+            echo "File does not exist, giving up. Check the Thanos sidecar for possible errors."
+            exit 1
+          fi
+
+          echo "Configuration found, starting Prometheus..."
+          exec /bin/prometheus \
+            --config.file=$config \
+            --storage.tsdb.no-lockfile \
+            --storage.tsdb.path=/var/prometheus/data \
+            --storage.tsdb.retention.time={{ .Values.prometheus.tsdb.retentionTime | default "24h" }} \
+            --storage.tsdb.min-block-duration=2h \
+            --storage.tsdb.max-block-duration=2h \
+            --web.enable-lifecycle \
+            --web.external-url=https://{{ .Values.prometheus.host | trim }} \
+            --web.enable-admin-api
+          {{- else }}
+          echo "Starting Prometheus..."
+          exec /bin/prometheus \
+            --config.file=/etc/prometheus/config/prometheus.yaml \
+            --storage.tsdb.no-lockfile \
+            --storage.tsdb.path=/var/prometheus/data \
+            --storage.tsdb.retention.time={{ .Values.prometheus.tsdb.retentionTime | default "24h" }} \
+            --web.enable-lifecycle \
+            {{- if .Values.prometheus.backup.enabled }}
+            --web.enable-admin-api \
+            {{- end }}
+            --web.external-url=https://{{ .Values.prometheus.host | trim }}
+          {{- end }}
         ports:
         - containerPort: 9090
           name: web
@@ -54,7 +96,7 @@ spec:
         readinessProbe:
           failureThreshold: 120
           httpGet:
-            path: /-/healthy
+            path: /-/ready
             port: web
           initialDelaySeconds: 15
           periodSeconds: 5
@@ -63,26 +105,34 @@ spec:
         resources:
 {{ toYaml .Values.prometheus.containers.prometheus.resources | indent 10 }}
         volumeMounts:
-        - mountPath: /etc/prometheus/config/
-          name: prometheus-kubermatic-config
+        {{- if .Values.prometheus.thanos.enabled }}
+        - name: config-shared
+          mountPath: /etc/prometheus-shared/
           readOnly: false
-        - mountPath: /etc/prometheus/rules/
-          name: prometheus-kubermatic-rules
+        {{- else }}
+        - name: config
+          mountPath: /etc/prometheus/config/
           readOnly: false
-        - mountPath: /var/prometheus/data
-          name: prometheus-kubermatic-db
+        {{- end }}
+        - name: rules
+          mountPath: /etc/prometheus/rules/
+          readOnly: false
+        - name: db
+          mountPath: /var/prometheus/data
           readOnly: false
           subPath: prometheus-db
         {{- if .Values.prometheus.volumes }}
         {{- range .Values.prometheus.volumes }}
-        - mountPath: {{ .mountPath }}
-          name: {{ .name }}
+        - name: {{ .name }}
+          mountPath: {{ .mountPath }}
           readOnly: true
         {{- end }}
         {{- end }}
 
+      {{- if not .Values.prometheus.thanos.enabled }}
       - name: reloader
-        image: jimmidyson/configmap-reload
+        image: '{{ .Values.prometheus.configReloaderImage.repository }}:{{ .Values.prometheus.configReloaderImage.tag }}'
+        imagePullPolicy: {{ .Values.prometheus.configReloaderImage.pullPolicy }}
         args:
         - --volume-dir=/etc/prometheus/config
         - --volume-dir=/etc/prometheus/rules
@@ -90,19 +140,20 @@ spec:
         resources:
 {{ toYaml .Values.prometheus.containers.reloader.resources | indent 10 }}
         volumeMounts:
-        - mountPath: /etc/prometheus/config/
-          name: prometheus-kubermatic-config
+        - name: config
+          mountPath: /etc/prometheus/config/
           readOnly: false
-        - mountPath: /etc/prometheus/rules/
-          name: prometheus-kubermatic-rules
+        - name: rules
+          mountPath: /etc/prometheus/rules/
           readOnly: false
         {{- if .Values.prometheus.volumes }}
         {{- range .Values.prometheus.volumes }}
-        - mountPath: {{ .mountPath }}
-          name: {{ .name }}
+        - name: {{ .name }}
+          mountPath: {{ .mountPath }}
           readOnly: true
         {{- end }}
         {{- end }}
+      {{- end }}
 
       {{- if .Values.prometheus.backup.enabled }}
       - name: backup
@@ -112,12 +163,12 @@ spec:
         - -c
         - while true; do sleep 1h; done
         volumeMounts:
-        - mountPath: /prometheus
-          name: prometheus-kubermatic-db
+        - name: db
+          mountPath: /prometheus
           readOnly: false
           subPath: prometheus-db
-        - mountPath: /backup
-          name: prometheus-backup
+        - name: backup
+          mountPath: /backup
           readOnly: false
         securityContext:
           runAsNonRoot: false
@@ -125,18 +176,59 @@ spec:
         resources:
 {{ toYaml .Values.prometheus.containers.backup.resources | indent 10 }}
       {{- end }}
-      serviceAccountName: prometheus-kubermatic
+
+      {{- if .Values.prometheus.thanos.enabled }}
+      - name: thanos
+        image: '{{ .Values.prometheus.thanos.image.repository }}:{{ .Values.prometheus.thanos.image.tag }}'
+        args:
+        - sidecar
+        - --tsdb.path=/prometheus
+        - --prometheus.url=http://localhost:9090
+        - --objstore.config-file=/etc/thanos/objstore.yaml
+        - --reloader.config-file=/etc/prometheus/config/prometheus.yaml
+        - --reloader.config-envsubst-file=/etc/prometheus-shared/prometheus.yaml
+        # New flag for migrating old blocks.
+        #- --shipper.upload-compacted-once
+        env:
+        - name: POD_NAME
+          valueFrom:
+            fieldRef:
+              fieldPath: metadata.name
+        ports:
+        - name: http-sidecar
+          containerPort: 10902
+        - name: grpc
+          containerPort: 10901
+        volumeMounts:
+        - name: db
+          mountPath: /prometheus
+          readOnly: false
+          subPath: prometheus-db
+        - name: config-shared
+          mountPath: /etc/prometheus-shared
+        - name: config
+          mountPath: /etc/prometheus/config
+        - name: thanos
+          mountPath: /etc/thanos
+        securityContext:
+          runAsNonRoot: false
+          runAsUser: 0
+        resources:
+{{ toYaml .Values.prometheus.containers.thanosSidecar.resources | indent 10 }}
+      {{- end }}
+
+      serviceAccountName: '{{ template "name" . }}'
       securityContext:
         fsGroup: 2000
         runAsNonRoot: true
         runAsUser: 1000
       volumes:
-      - name: prometheus-kubermatic-config
+      - name: config
         configMap:
-          name: prometheus-kubermatic-config
-      - name: prometheus-kubermatic-rules
+          name: '{{ template "name" . }}-config'
+      - name: rules
         configMap:
-          name: prometheus-kubermatic-rules
+          name: '{{ template "name" . }}-rules'
       {{- if .Values.prometheus.volumes }}
       {{- range .Values.prometheus.volumes }}
       - name: {{ .name }}
@@ -150,32 +242,43 @@ spec:
       {{- end }}
       {{- end }}
       {{- if .Values.prometheus.backup.enabled }}
-      - name: prometheus-backup
+      - name: backup
         emptyDir: {}
+      {{- end }}
+      {{- if .Values.prometheus.thanos.enabled }}
+      - name: config-shared
+        emptyDir: {}
+      - name: thanos
+        secret:
+          secretName: '{{ template "name" . }}-thanos'
       {{- end }}
       nodeSelector:
 {{ toYaml .Values.prometheus.nodeSelector | indent 8 }}
       affinity:
-{{ toYaml .Values.prometheus.affinity | indent 8 }}
+{{ (tpl (toYaml .Values.prometheus.affinity) .) | fromYaml | toYaml | indent 8 }}
       tolerations:
 {{ toYaml .Values.prometheus.tolerations | indent 8 }}
   volumeClaimTemplates:
   - metadata:
-      name: prometheus-kubermatic-db
+      name: db
     spec:
       accessModes:
       - ReadWriteOnce
       resources:
         requests:
           storage: {{ .Values.prometheus.storageSize }}
-      storageClassName: kubermatic-fast
+      {{- with .Values.prometheus.storageClass }}
+      storageClassName: {{ . }}
+      {{- end }}
+{{ end }}
+
 ---
 apiVersion: policy/v1beta1
 kind: PodDisruptionBudget
 metadata:
-  name: prometheus-kubermatic
+  name: '{{ template "name" . }}'
 spec:
   minAvailable: 1
   selector:
     matchLabels:
-      app: prometheus-kubermatic
+      app: '{{ template "name" . }}'
